### ISSUE TITLE
Ability To Ping Role(s) When A Raid Is Posted

### ISSUE THREAD

**Issue by Deadmano** [DasithKuruppu/uglyBot#110]
Currently you have to manually ping roles when a raid is posted. It'd be pretty neat if we could just post a raid and specify which roles will be pinged so they get notified of the raid sign-up.

**Comment by DasithKuruppu** [comment]
Currently this would be done automatically ~ 45 mins to ~ 1 hour before the raids starts by pinging all the users on raid. Will add stuff later on to fine tune this with more control for the creators if necessary. Closing this for new feel free to open tickets with specific requests that are needed on top of the basic functionality available now.
