### ISSUE TITLE
Emojis/icons

### ISSUE THREAD

**Issue by Zephereth** [DasithKuruppu/uglyBot#118]
I have an issue where the class and artifact icons aren't showing up in the top section of the bot's UI.  The icons show up just fine in the lower section where you first choose your classes and artifacts.  I'm not sure if I did something incorrect or if this is known.  Thanks!

![Capture1](https://user-images.githubusercontent.com/119073149/220189484-ae9c1177-a8ff-479a-a9c1-809693b3ce0f.PNG)
![Capture](https://user-images.githubusercontent.com/119073149/220189486-e622560c-25de-42e4-b160-8c978bd0e58c.PNG)

**Comment by Deadmano** [comment]
You need to enable just the `Use External Emoji` permission for the
***@***.***` role in that specific channel and any other channels you plan
to use the bot in.

**Comment by Deadmano** [comment]
You need to enable just the `Use External Emoji` permission for the `@everyone` role in that specific channel and any other channels you plan to use the bot in.

**Comment by Zephereth** [comment]
Thanks for the quick response, that fixed it!

**Comment by DasithKuruppu** [comment]
Glad this got resolved so quick for you @Zephereth , and thanks for answering it @Deadmano
