### ISSUE TITLE
Add /Profile Command

### ISSUE THREAD

**Issue by Deadmano** [DasithKuruppu/uglyBot#64]
It would be nice to have a `/profile` command wherein you can enter information about your characters and self, such as;

- Timezone
Being able to set your timezone so the bot takes that into when creating a raid.

- Player Handle
It should ask for your player handle, so that can be displayed on the sign-up as `character@handle(#discriminator)`.

- Class Character Name
Being able to set a name for each class you have, so when you sign up it displays the character name instead of your Discord handle.

- Artifacts Per Class
It will allow you to add a list of artifacts you have for each character and should specify the character name.

- Mounts Per Class
Same as artifacts, but for mounts!

**Comment by DasithKuruppu** [comment]
This is now supported.
