### ISSUE TITLE
Artifacts Based On Content

### ISSUE THREAD

**Issue by Deadmano** [DasithKuruppu/uglyBot#65]
Consider adding a config option for each trial, whereby you can specify how many debuffs/utility/mitigation artifacts you would like at minimum, as well as who should be running them (tank/healer) etc defaulting to sane options such as healers on mitigation first etc.

The current implementation is that it will assign the best artifacts across the sign-ups, but that also means that in for example TOMM/ZCM you could have a healer assigned to Blades instead of the much needed Tiamat's Orb. These certain mitigation artifacts should be prioritised across supports, and potentially extend to things such as a Tutor/Black Scorpion/Drizzt etc.

You could technically only have the healer specify mitigation artifacts, but in some content that is not required (Crown for example) so that'd be a waste of an artifact slot and manually editing artifacts each time could potentially be rather annoying.

**Comment by DasithKuruppu** [comment]
Artifacts are sorted considering the trial type as well now
