### ISSUE TITLE
Ability To Add Custom Events

### ISSUE THREAD

**Issue by Deadmano** [DasithKuruppu/uglyBot#66]
Right now the bot can only handle pre-set events. If you added a "custom" option to the list of events that takes in a "Name" and additionally the amount of sign-ups/roles required it means that custom content could be run such as specific dungeon farming, dragon hunts, stronghold runs, etc.

I do like the approach of keeping it simple and endgame trial specific, but there is also no reason why it can't handle custom events since it is pretty much geared to handle any piece of content with a bit of config.

**Comment by DasithKuruppu** [comment]
Added in generic 5 person and 10 person raid options for this instead.
