### ISSUE TITLE
Display Only Chosen Artifacts Under User

### ISSUE THREAD

**Issue by Deadmano** [DasithKuruppu/uglyBot#67]
Right now all the artifacts a user has is displayed under their name in the event sign-up. It adds a lot of clutter and the sorted artifacts appear above it, creating even more clutter. Could the UX be improved by sorting artifacts and displaying the proposed artifact to use under the specific user instead?

By default is should be empty, and a note at the bottom should mention sorting. Or, better yet; automatically sort artifacts each time a new person signs up but keep the ability to manually sort in the event that someone forgot to update their artifacts and it needs to be re-sorted.

**Comment by DasithKuruppu** [comment]
Decided to not go for this approach, since organisers still want to see all artifacts etc a user has at a glance
